export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    me: "/auth/me",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
  },
  accessControl: {
    users: "/users",
    roles: {
      base: "/access-control/roles",
      all: "/access-control/roles/all",
    },
    modules: "/access-control/modules",
    actions: "/access-control/actions",
  },
  masters: {
    root: "/masters",
    detailedActivities: "/masters/detailed-activities",
    detailedActivitiesSelect: "/masters/detailed-activities/select",
    mgaActivities: "/masters/mga-activities",
    mgaActivityDetailedActivities: (id: string) => `/masters/mga-activities/${id}/detailed-activities`,
    mgaActivityDetailedRelations: (id: string) => `/masters/mga-activities/${id}/detailed-relations`,
    mgaActivityDetailedRelationsRemove: (id: string, detailedId: string) => `/masters/mga-activities/${id}/detailed-relations/${detailedId}`,
    productsSelect: "/masters/products/select",
    rubricsSelect: "/masters/rubrics/select",
    budgetModifications: "/masters/budget-modifications",
    variables: "/masters/variables",
  },
  audit: "/audit",
  financial: {
    needs: "/financial/needs",
    previousStudies: "/financial/previous-studies",
    masterContracts: "/financial/master-contracts",
    projects: "/financial/projects",
    projectsSelect: "/financial/projects/select",
    poaiPpa: "/financial/poai-ppa",
    poaiPpaProjectYears: (projectId: string) => `/financial/poai-ppa/project/${projectId}/years`,
    poaiPpaProjectSummary: (projectId: string) => `/financial/poai-ppa/project/${projectId}/summary`,
    poaiPpaProjectEvolution: (projectId: string) => `/financial/poai-ppa/project/${projectId}/evolution`,
    poaiPpaTrends: "/financial/poai-ppa/trends",
    cdpsTable: "/financial/cdps/positions/table",
    cdpPositionDetail: (id: string) => `/financial/cdps/positions/${id}`,
    cdpPositionDetailedActivities: (positionId: string) => `/financial/cdps/positions/${positionId}/detailed-activities`,
    cdpPositionDetailedActivitiesRemove: (positionId: string, activityId: string) => `/financial/cdps/positions/${positionId}/detailed-activities/${activityId}`,
    cdpPositionConsume: (positionId: string) => `/financial/cdps/positions/${positionId}/consume`,
  },
}