export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    me: "/auth/me",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
  },
  accessControl: {
    users: "/users",
    roles: {
      base: "/access-control/roles",
      all: "/access-control/roles/all",
    },
    modules: "/access-control/modules",
    actions: "/access-control/actions",
  },
  masters: {
    root: "/masters",
    detailedActivities: "/masters/detailed-activities",
    detailedActivitiesSelect: "/masters/detailed-activities/select",
    mgaActivities: "/masters/mga-activities",
    mgaActivityDetailedActivities: (id: string) => `/masters/mga-activities/${id}/detailed-activities`,
    mgaActivityDetailedRelations: (id: string) => `/masters/mga-activities/${id}/detailed-relations`,
    mgaActivityDetailedRelationsRemove: (id: string, detailedId: string) => `/masters/mga-activities/${id}/detailed-relations/${detailedId}`,
    productsSelect: "/masters/products/select",
    rubricsSelect: "/masters/rubrics/select",
    budgetModifications: "/masters/budget-modifications",
    variables: "/masters/variables",
    variableGoals: "/masters/variable-goals",
    variableQuadrenniums: "/masters/variable-quadrenniums",
    indicators: "/masters/indicators",
    actionPlanIndicators: "/masters/action-plan-indicators",
    actionPlanIndicatorGoals: "/masters/action-plan-indicators-goals",
    actionPlanIndicatorQuadrenniums: "/masters/action-plan-indicators-quadrenniums",
    indicatorCatalogs: "/masters/indicators/catalogs", // New endpoint for catalogs
    indicativePlanIndicatorGoals: "/masters/indicative-plan-indicators-goals",
    indicativePlanIndicatorQuadrenniums: "/masters/indicative-plan-indicators-quadrenniums",
    indicativePlanIndicatorQuadrenniumsByIndicator: (id: string) => `/masters/indicative-plan-indicators-quadrenniums/by-indicator/${id}`,
    // Indicator Variables
    indicatorVariables: (id: string) => `/masters/indicators/${id}/variables`,
    indicatorVariablesDissociate: (id: string, variableId: string) => `/masters/indicators/${id}/variables/${variableId}`,
    // Action Plan Indicator Variables
    actionPlanIndicatorVariables: (id: string) => `/masters/action-plan-indicators/${id}/variables`,
    actionPlanIndicatorVariablesDissociate: (id: string, variableId: string) => `/masters/action-plan-indicators/${id}/variables/${variableId}`,
    // Action Plan Indicator Projects
    actionPlanIndicatorProjects: (id: string) => `/masters/action-plan-indicators/${id}/projects`,
    actionPlanIndicatorProjectsDissociate: (id: string, projectId: string) => `/masters/action-plan-indicators/${id}/projects/${projectId}`,
  },
  audit: "/audit",
  financial: {
    needs: "/financial/needs",
    previousStudies: "/financial/previous-studies",
    masterContracts: "/financial/master-contracts",
    projects: "/financial/projects",
    projectsSelect: "/financial/projects/select",
    poaiPpa: "/financial/poai-ppa",
    poaiPpaProjectYears: (projectId: string) => `/financial/poai-ppa/project/${projectId}/years`,
    poaiPpaProjectSummary: (projectId: string) => `/financial/poai-ppa/project/${projectId}/summary`,
    poaiPpaProjectEvolution: (projectId: string) => `/financial/poai-ppa/project/${projectId}/evolution`,
    poaiPpaTrends: "/financial/poai-ppa/trends",
    cdpsTable: "/financial/cdps/positions/table",
    cdpPositionDetail: (id: string) => `/financial/cdps/positions/${id}`,
    cdpPositionDetailedActivities: (positionId: string) => `/financial/cdps/positions/${positionId}/detailed-activities`,
    cdpPositionDetailedActivitiesRemove: (positionId: string, activityId: string) => `/financial/cdps/positions/${positionId}/detailed-activities/${activityId}`,
    cdpPositionConsume: (positionId: string) => `/financial/cdps/positions/${positionId}/consume`,
  },
  sub: {
    variableAdvances: {
      base: "/sub/variable-advances",
      contextual: {
        actionIndicator: (id: string) => `/sub/variable-advances/contextual/action-indicator/${id}`,
        indicativeIndicator: (id: string) => `/sub/variable-advances/contextual/indicative-indicator/${id}`,
      },
    },
  },
}