export const endpoints = {
  auth: {
    login: "/public/auth/login",
    register: "/public/auth/register",
    verifyEmail: "/public/auth/verify-email",
    resendVerification: "/public/auth/resend-verification",
    forgotPassword: "/public/auth/forgot-password",
    resetPassword: "/public/auth/reset-password",
    me: "/public/auth/me",
    logout: "/public/auth/logout",
    refresh: "/public/auth/refresh",
    wsToken: "/public/auth/ws-token",
  },
  accessControl: {
    users: "/public/users",
    roles: {
      base: "/public/access-control/roles",
      all: "/public/access-control/roles/all",
    },
    modules: "/public/access-control/modules",
    actions: "/public/access-control/actions",
  },
  masters: {
    root: "/spd/masters",
    detailedActivities: "/spd/masters/detailed-activities",
    detailedActivitiesSelect: "/spd/masters/detailed-activities/select",
    mgaActivities: "/spd/masters/mga-activities",
    mgaActivityDetailedActivities: (id: string) => `/spd/masters/mga-activities/${id}/detailed-activities`,
    mgaActivityDetailedRelations: (id: string) => `/spd/masters/mga-activities/${id}/detailed-relations`,
    mgaActivityDetailedRelationsRemove: (id: string, detailedId: string) => `/spd/masters/mga-activities/${id}/detailed-relations/${detailedId}`,
    productsSelect: "/spd/masters/products/select",
    rubricsSelect: "/spd/masters/rubrics/select",
    budgetModifications: "/spd/masters/budget-modifications",
    variables: "/spd/masters/variables",
    variableLocations: (id: string) => `/spd/masters/variables/${id}/locations`,
    variableLocationsDissociate: (id: string, locationId: string) => `/spd/masters/variables/${id}/locations/${locationId}`,
    variableGoals: "/spd/masters/variable-goals",
    variableQuadrenniums: "/spd/masters/variable-quadrenniums",
    indicators: "/spd/masters/indicators",
    actionPlanIndicators: "/spd/masters/action-plan-indicators",
    actionPlanIndicatorGoals: "/spd/masters/action-plan-indicators-goals",
    actionPlanIndicatorQuadrenniums: "/spd/masters/action-plan-indicators-quadrenniums",
    indicatorCatalogs: "/spd/masters/indicators/catalogs",
    indicativePlanIndicatorGoals: "/spd/masters/indicative-plan-indicators-goals",
    indicativePlanIndicatorQuadrenniums: "/spd/masters/indicative-plan-indicators-quadrenniums",
    indicativePlanIndicatorQuadrenniumsByIndicator: (id: string) => `/spd/masters/indicative-plan-indicators-quadrenniums/by-indicator/${id}`,
    // Indicator Variables
    indicatorVariables: (id: string) => `/spd/masters/indicators/${id}/variables`,
    indicatorVariablesDissociate: (id: string, variableId: string) => `/spd/masters/indicators/${id}/variables/${variableId}`,
    // Action Plan Indicator Variables
    actionPlanIndicatorVariables: (id: string) => `/spd/masters/action-plan-indicators/${id}/variables`,
    actionPlanIndicatorVariablesDissociate: (id: string, variableId: string) => `/spd/masters/action-plan-indicators/${id}/variables/${variableId}`,
    // Action Plan Indicator Projects
    actionPlanIndicatorProjects: (id: string) => `/spd/masters/action-plan-indicators/${id}/projects`,
    actionPlanIndicatorProjectsDissociate: (id: string, projectId: string) => `/spd/masters/action-plan-indicators/${id}/projects/${projectId}`,
    locations: "/spd/masters/locations",
    locationsSelect: "/spd/masters/locations/select",
    communesSelect: "/spd/masters/communes/select",
    indicativePlanIndicatorLocations: (id: string) => `/spd/masters/indicative-plan-indicators/${id}/locations`,
    indicativePlanIndicatorLocationsDissociate: (id: string, locationId: string) => `/spd/masters/indicative-plan-indicators/${id}/locations/${locationId}`,
    actionPlanIndicatorLocations: (id: string) => `/spd/masters/action-plan-indicators/${id}/locations`,
    actionPlanIndicatorLocationsDissociate: (id: string, locationId: string) => `/spd/masters/action-plan-indicators/${id}/locations/${locationId}`,
    // Location-based indicator queries
    indicatorsByLocation: (communeId: string) => `/spd/masters/indicative-plan-indicators/locations/by-commune/${communeId}`,
    actionPlanIndicatorsByLocation: (communeId: string) => `/spd/masters/action-plan-indicators/locations/by-commune/${communeId}`,
    indicatorLocationVariables: (id: string, type: 'indicative' | 'action') =>
      type === 'indicative'
        ? `/spd/masters/indicative-plan-indicators/${id}/locations/variables`
        : `/spd/masters/action-plan-indicators/${id}/locations/variables`,
    // Indicator User Assignments
    indicatorUsers: (id: string) => `/spd/masters/indicators/${id}/users`,
    indicatorUsersRemove: (id: string, userId: string) => `/spd/masters/indicators/${id}/users/${userId}`,
    actionPlanIndicatorUsers: (id: string) => `/spd/masters/action-plan-indicators/${id}/users`,
    actionPlanIndicatorUsersRemove: (id: string, userId: string) => `/spd/masters/action-plan-indicators/${id}/users/${userId}`,
    // Variable User Assignments
    variableUsers: (id: string) => `/spd/masters/variables/${id}/users`,
    variableUsersRemove: (id: string, userId: string) => `/spd/masters/variables/${id}/users/${userId}`,
  },
  exports: {
    create: "/public/exports/data",
    status: (id: string) => `/public/exports/data/${id}`,
    list: "/public/exports/data",
  },
  notifications: {
    list: "/public/notifications",
    unreadCount: "/public/notifications/unread-count",
    markRead: (id: string) => `/public/notifications/${id}/read`,
    readAll: "/public/notifications/read-all",
  },
  audit: "/public/audit",
  financial: {
    needs: "/spd/financial/needs",
    previousStudies: "/spd/financial/previous-studies",
    masterContracts: "/spd/financial/master-contracts",
    projects: "/spd/financial/projects",
    projectsSelect: "/spd/financial/projects/select",
    poaiPpa: "/spd/financial/poai-ppa",
    poaiPpaProjectYears: (projectId: string) => `/spd/financial/poai-ppa/project/${projectId}/years`,
    poaiPpaProjectSummary: (projectId: string) => `/spd/financial/poai-ppa/project/${projectId}/summary`,
    poaiPpaProjectEvolution: (projectId: string) => `/spd/financial/poai-ppa/project/${projectId}/evolution`,
    poaiPpaTrends: "/spd/financial/poai-ppa/trends",
    cdpsTable: "/spd/financial/cdps/positions/table",
    cdpPositionDetail: (id: string) => `/spd/financial/cdps/positions/${id}`,
    cdpPositionDetailedActivities: (positionId: string) => `/spd/financial/cdps/positions/${positionId}/detailed-activities`,
    cdpPositionDetailedActivitiesRemove: (positionId: string, activityId: string) => `/spd/financial/cdps/positions/${positionId}/detailed-activities/${activityId}`,
    cdpPositionConsume: (positionId: string) => `/spd/financial/cdps/positions/${positionId}/consume`,
    masterContractCdpPositions: (id: string) => `/spd/financial/master-contracts/${id}/cdp-positions`,
  },
  sub: {
    variableAdvances: {
      base: "/spd/sub/variable-advances",
      contextual: {
        actionIndicator: (id: string) => `/spd/sub/variable-advances/contextual/action-indicator/${id}`,
        indicativeIndicator: (id: string) => `/spd/sub/variable-advances/contextual/indicative-indicator/${id}`,
      },
      locations: {
        variable: (variableId: string) => `/spd/sub/variable-advances/locations/variable/${variableId}`,
        indicator: (indicatorId: string, type: string) => `/spd/sub/variable-advances/locations/indicator/${indicatorId}/${type}`,
      },
      withLocations: (variableId: string) => `/spd/sub/variable-advances/with-locations/variable/${variableId}`,
      details: (variableId: string) => `/spd/sub/variable-advances/${variableId}/details`,
    },
    indicatorAdvances: {
      actionDetailed: (id: string) => `/spd/sub/indicator-advances/action/${id}/detailed`,
      indicativeDetailed: (id: string) => `/spd/sub/indicator-advances/indicative/${id}/detailed`,
    },
    my: {
      indicativeIndicators: "/spd/sub/my/indicative-indicators",
      actionIndicators: "/spd/sub/my/action-indicators",
      variables: "/spd/sub/my/variables",
    },
  },
}